SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO as II
INNER JOIN ITEM_TREE as IT
ON IT.ITEM_ID = II.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID
                            FROM ITEM_INFO
                           WHERE ITEM_INFO.RARITY = 'RARE')
ORDER BY II.ITEM_ID DESC
